services:
  api:
    build: .
    ports:
      - "8032:8000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A app.celery_app.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - API_URL=http://api:8000
    depends_on:
      - api
      - redis
    restart: unless-stopped

  beat:
    build: .
    command: celery -A app.celery_app.celery beat --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - API_URL=http://api:8000
    depends_on:
      - api
      - redis
    restart: unless-stopped